name: Remote workflow

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
      callback_url:
        description: "Webhook url"
      pr_sha:
        description: "PR sha number"

jobs:
  run-checks:
     runs-on: ubuntu-latest
     steps:
        - name: "Run tests"
          run: |
            echo "Starting dummy test process..."
            # Simulate a long-running process (e.g., sleep for 1 minute)
            sleep 80  # This will keep the action running for 60 seconds
            exit 1
            echo "Dummy tests complete."

        - name: Notify the original repo
          if: always()
          run: |
            STATUS="failure"
            if [ "${{ job.status }}" == "success" ]; then
              STATUS="success"
            fi
            curl -X POST -H "Authorization: token ${{secrets.TEST_TOKEN_JOY}}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -H "Content-Type: application/json" \
                 https://api.github.com/repos/sangeet-joy-tw/semantic-release-POC/dispatches \
                 -d '{"event_type": "remote-check-done", "client_payload": { "pr_number": "${{github.event.inputs.pr_number}}", "status": "'${STATUS}'", "pr_sha": "${{github.event.inputs.pr_sha}}"} }'

 